# This file was generated by GoReleaser. DO NOT EDIT.
cask "blues-traveler" do
  desc "Claude Code hooks management tool - 'The hook brings you back'"
  homepage "https://github.com/klauern/blues-traveler"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "blues-traveler"

  on_macos do
    on_intel do
      url "https://github.com/klauern/blues-traveler/releases/download/v0.1.2/blues-traveler_Darwin_x86_64.tar.gz"
      sha256 "4b3d7420828c14c9377b4a2186beb43a521fcbdb668580dbe9fcac6878c5a454"
    end
    on_arm do
      url "https://github.com/klauern/blues-traveler/releases/download/v0.1.2/blues-traveler_Darwin_arm64.tar.gz"
      sha256 "bea4d087769ffbe9f428d01d9cc10cb6eaac223ef2b9002c2b937085270302fe"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/klauern/blues-traveler/releases/download/v0.1.2/blues-traveler_Linux_x86_64.tar.gz"
      sha256 "260ec3e34cb635385a89b7825fde1c143dfd8a4272ae0ce2be6f6a99ac63ddb2"
    end
    on_arm do
      url "https://github.com/klauern/blues-traveler/releases/download/v0.1.2/blues-traveler_Linux_arm64.tar.gz"
      sha256 "63df56a5c7943c85e768f47a8144485dba42021714ab39aa27f9bc629ad11c80"
    end
  end

  # No zap stanza required
end
