# This file was generated by GoReleaser. DO NOT EDIT.
cask "blues-traveler" do
  desc "Claude Code hooks management tool - 'The hook brings you back'"
  homepage "https://github.com/klauern/blues-traveler"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "blues-traveler"

  on_macos do
    on_intel do
      url "https://github.com/klauern/blues-traveler/releases/download/v0.1.3/blues-traveler_Darwin_x86_64.tar.gz"
      sha256 "9251e23c83e9d0d86c211b74ff468f64509241531a7d3e79d054ed690c11c12e"
    end
    on_arm do
      url "https://github.com/klauern/blues-traveler/releases/download/v0.1.3/blues-traveler_Darwin_arm64.tar.gz"
      sha256 "72ccc1f6ccb3a8bad5e52027389f7ef3a586f0d2bc67ccedfbb0df35d912bdaf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/klauern/blues-traveler/releases/download/v0.1.3/blues-traveler_Linux_x86_64.tar.gz"
      sha256 "62c94169fb95ee6aab78b95ce28d42d4af00526961f1191bca09c1a91e02aa7f"
    end
    on_arm do
      url "https://github.com/klauern/blues-traveler/releases/download/v0.1.3/blues-traveler_Linux_arm64.tar.gz"
      sha256 "d61233b73989f3e7d9b5a41d3ce6391222f77ea69a80add68a70235d71d5e514"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/blues-traveler"]
    end
  end

  # No zap stanza required
end
