# This file was generated by GoReleaser. DO NOT EDIT.
cask "blues-traveler" do
  desc "Claude Code hooks management tool - 'The hook brings you back'"
  homepage "https://github.com/klauern/blues-traveler"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "blues-traveler"

  on_macos do
    on_intel do
      url "https://github.com/klauern/blues-traveler/releases/download/v0.1.0/blues-traveler_Darwin_x86_64.tar.gz"
      sha256 "2735fab67dd1e6addef681aadeb7e6e21d60770a74664fa7c3a0780e65b83720"
    end
    on_arm do
      url "https://github.com/klauern/blues-traveler/releases/download/v0.1.0/blues-traveler_Darwin_arm64.tar.gz"
      sha256 "ddb0dbde642803a39ae62e87737f38f4e037d20c6bd971c6d6091800d74d0c57"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/klauern/blues-traveler/releases/download/v0.1.0/blues-traveler_Linux_x86_64.tar.gz"
      sha256 "47b358e08e9f2b169e6cf7ec0899b962c8bf7bd11c435876ebb44854705550b2"
    end
    on_arm do
      url "https://github.com/klauern/blues-traveler/releases/download/v0.1.0/blues-traveler_Linux_arm64.tar.gz"
      sha256 "158093475e66ff547aba47a9ad09e02b98c8554cebd62dca0a6cb7fa326ff2d4"
    end
  end

  # No zap stanza required
end
